import {
  University,
  Pattern,
  Branch,
  AcademicYear,
  Semester,
  Subject,
  Unit,
  Topic,
  SyllabusItem,
  ContentSource,
  Question,
  QuestionOccurrence,
  QuestionCluster,
  QuestionClusterMember,
  Answer,
  Note,
  Quiz,
  QuizQuestion,
  QuizAttempt,
  StudentProgress,
  StudyPlan,
  StudyPlanTask,
  Product,
  Order,
  Payment,
  Entitlement,
  VerificationRecord,
  User,
  StudySession,
  ExamModeRecord,
  RevisionRecord,
} from './types';

export const SEED_UNIVERSITIES: University[] = [
  {
    id: 'uni-sppu',
    code: 'SPPU',
    name: 'Savitribai Phule Pune University',
    state: 'Maharashtra',
    country: 'India',
    website: 'http://www.unipune.ac.in',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_PATTERNS: Pattern[] = [
  {
    id: 'pat-2024',
    university_id: 'uni-sppu',
    name: '2024 Pattern (NEP)',
    code: '2024-pattern',
    effective_year: 2024,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pat-2019',
    university_id: 'uni-sppu',
    name: '2019 Pattern',
    code: '2019-pattern',
    effective_year: 2019,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_BRANCHES: Branch[] = [
  {
    id: 'branch-comp',
    code: 'COMP',
    name: 'Computer Engineering',
    description: 'SPPU Computer Engineering curriculum, previous year question intelligence, and exam-focused notes.',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'branch-it',
    code: 'IT',
    name: 'Information Technology',
    description: 'Comprehensive exam intelligence for IT subjects across semesters.',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'branch-aids',
    code: 'AI-DS',
    name: 'Artificial Intelligence & Data Science',
    description: 'Specialized notes, PYQs, and priority models for AI & Data Science.',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'branch-entc',
    code: 'E&TC',
    name: 'Electronics & Telecommunication',
    description: 'Exam preparation tools for Core E&TC subjects.',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_ACADEMIC_YEARS: AcademicYear[] = [
  {
    id: 'ay-fe-comp',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    code: 'FE',
    name: 'First Year Engineering',
    year_number: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ay-se-comp',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    code: 'SE',
    name: 'Second Year Engineering',
    year_number: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ay-te-it',
    pattern_id: 'pat-2019',
    branch_id: 'branch-it',
    code: 'TE',
    name: 'Third Year Engineering',
    year_number: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ay-be-aids',
    pattern_id: 'pat-2019',
    branch_id: 'branch-aids',
    code: 'BE',
    name: 'Final Year Engineering',
    year_number: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ay-se-entc',
    pattern_id: 'pat-2024',
    branch_id: 'branch-entc',
    code: 'SE',
    name: 'Second Year Engineering',
    year_number: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ay-se-2024',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    code: 'SE',
    name: 'Second Year Engineering (2024)',
    year_number: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_SEMESTERS: Semester[] = [
  {
    id: 'sem-2-comp',
    academic_year_id: 'ay-fe-comp',
    semester_number: 2,
    name: 'Semester 2',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sem-3',
    academic_year_id: 'ay-se-comp',
    semester_number: 3,
    name: 'Semester 3',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sem-4',
    academic_year_id: 'ay-se-comp',
    semester_number: 4,
    name: 'Semester 4',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sem-6-it',
    academic_year_id: 'ay-te-it',
    semester_number: 6,
    name: 'Semester 6',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sem-8-aids',
    academic_year_id: 'ay-be-aids',
    semester_number: 8,
    name: 'Semester 8',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sem-3-entc',
    academic_year_id: 'ay-se-entc',
    semester_number: 3,
    name: 'Semester 3',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_SUBJECTS: Subject[] = [
  {
    id: 'sub-dbms',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    code: '210241',
    name: 'Database Management Systems',
    short_name: 'DBMS',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-dsa',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    code: '210242',
    name: 'Data Structures & Algorithms',
    short_name: 'DSA',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-oop',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    code: '210243',
    name: 'Object Oriented Programming',
    short_name: 'OOP',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-os',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    code: '210244',
    name: 'Operating Systems',
    short_name: 'OS',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-toc',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    code: '210245',
    name: 'Theory of Computation',
    short_name: 'TOC',
    total_units: 6,
    total_credits: 3,
    is_popular: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // FE Computer (Semester 2)
  {
    id: 'sub-em2',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-2-comp',
    code: '107008',
    name: 'Engineering Mathematics-II',
    short_name: 'EM-II',
    total_units: 6,
    total_credits: 4,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-bxe',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-2-comp',
    code: '104010',
    name: 'Basic Electronics Engineering',
    short_name: 'BXE',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-pps',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-2-comp',
    code: '110005',
    name: 'Programming and Problem Solving',
    short_name: 'PPS',
    total_units: 6,
    total_credits: 4,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-phy',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-2-comp',
    code: '107002',
    name: 'Engineering Physics',
    short_name: 'PHY',
    total_units: 6,
    total_credits: 3,
    is_popular: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-sme',
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-2-comp',
    code: '102003',
    name: 'Systems in Mechanical Engineering',
    short_name: 'SME',
    total_units: 6,
    total_credits: 3,
    is_popular: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // TE IT (Semester 6)
  {
    id: 'sub-cns',
    pattern_id: 'pat-2019',
    branch_id: 'branch-it',
    semester_id: 'sem-6-it',
    code: '314451',
    name: 'Computer Networks & Security',
    short_name: 'CNS',
    total_units: 6,
    total_credits: 4,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-wad',
    pattern_id: 'pat-2019',
    branch_id: 'branch-it',
    semester_id: 'sem-6-it',
    code: '314452',
    name: 'Web Application Development',
    short_name: 'WAD',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-dsba',
    pattern_id: 'pat-2019',
    branch_id: 'branch-it',
    semester_id: 'sem-6-it',
    code: '314453',
    name: 'Data Science & Big Data Analytics',
    short_name: 'DSBDA',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-cc',
    pattern_id: 'pat-2019',
    branch_id: 'branch-it',
    semester_id: 'sem-6-it',
    code: '314454',
    name: 'Cloud Computing',
    short_name: 'CC',
    total_units: 6,
    total_credits: 3,
    is_popular: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-smd',
    pattern_id: 'pat-2019',
    branch_id: 'branch-it',
    semester_id: 'sem-6-it',
    code: '314455',
    name: 'Software Modeling and Design',
    short_name: 'SMD',
    total_units: 6,
    total_credits: 3,
    is_popular: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // BE AI & Data Science (Semester 8)
  {
    id: 'sub-dlnn',
    pattern_id: 'pat-2019',
    branch_id: 'branch-aids',
    semester_id: 'sem-8-aids',
    code: '417521',
    name: 'Deep Learning & Neural Networks',
    short_name: 'DLNN',
    total_units: 6,
    total_credits: 4,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-nlp',
    pattern_id: 'pat-2019',
    branch_id: 'branch-aids',
    semester_id: 'sem-8-aids',
    code: '417522',
    name: 'Natural Language Processing',
    short_name: 'NLP',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-rl',
    pattern_id: 'pat-2019',
    branch_id: 'branch-aids',
    semester_id: 'sem-8-aids',
    code: '417523',
    name: 'Reinforcement Learning',
    short_name: 'RL',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-bda',
    pattern_id: 'pat-2019',
    branch_id: 'branch-aids',
    semester_id: 'sem-8-aids',
    code: '417524',
    name: 'Big Data Analytics & MLOps',
    short_name: 'BDA',
    total_units: 6,
    total_credits: 3,
    is_popular: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-asr',
    pattern_id: 'pat-2019',
    branch_id: 'branch-aids',
    semester_id: 'sem-8-aids',
    code: '417525',
    name: 'Autonomous Systems & Robotics',
    short_name: 'ASR',
    total_units: 6,
    total_credits: 3,
    is_popular: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // SE E&TC (Semester 3)
  {
    id: 'sub-ss',
    pattern_id: 'pat-2024',
    branch_id: 'branch-entc',
    semester_id: 'sem-3-entc',
    code: '204181',
    name: 'Signals & Systems',
    short_name: 'SS',
    total_units: 6,
    total_credits: 4,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-eca',
    pattern_id: 'pat-2024',
    branch_id: 'branch-entc',
    semester_id: 'sem-3-entc',
    code: '204182',
    name: 'Electronic Circuits & Applications',
    short_name: 'ECA',
    total_units: 6,
    total_credits: 4,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-dsd',
    pattern_id: 'pat-2024',
    branch_id: 'branch-entc',
    semester_id: 'sem-3-entc',
    code: '204183',
    name: 'Digital System Design',
    short_name: 'DSD',
    total_units: 6,
    total_credits: 3,
    is_popular: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-nt',
    pattern_id: 'pat-2024',
    branch_id: 'branch-entc',
    semester_id: 'sem-3-entc',
    code: '204184',
    name: 'Network Theory',
    short_name: 'NT',
    total_units: 6,
    total_credits: 3,
    is_popular: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'sub-cs',
    pattern_id: 'pat-2024',
    branch_id: 'branch-entc',
    semester_id: 'sem-3-entc',
    code: '204185',
    name: 'Control Systems',
    short_name: 'CS',
    total_units: 6,
    total_credits: 3,
    is_popular: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_UNITS: Unit[] = [
  // DBMS Units (sub-dbms)
  {
    id: 'unit-dbms-1',
    subject_id: 'sub-dbms',
    unit_number: 1,
    title: 'Introduction to DBMS & ER Modeling',
    description: 'Database architecture, 3-schema architecture, ER diagrams, Strong vs Weak Entity sets.',
    weightage_percentage: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dbms-2',
    subject_id: 'sub-dbms',
    unit_number: 2,
    title: 'Relational Model & Relational Algebra',
    description: 'Codd rules, Relational Algebra operators, SQL queries, Join operations.',
    weightage_percentage: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dbms-3',
    subject_id: 'sub-dbms',
    unit_number: 3,
    title: 'Database Design & Normalization',
    description: 'Functional Dependencies, 1NF, 2NF, 3NF, BCNF, Lossless Join, Dependency Preservation.',
    weightage_percentage: 24,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dbms-4',
    subject_id: 'sub-dbms',
    unit_number: 4,
    title: 'Transaction Management & Concurrency Control',
    description: 'ACID properties, Schedule Serializability, 2PL, Deadlocks, Timestamp ordering.',
    weightage_percentage: 20,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dbms-5',
    subject_id: 'sub-dbms',
    unit_number: 5,
    title: 'Database Recovery Systems',
    description: 'Log-based recovery, Checkpointing, Shadow Paging, ARIES algorithm, Failure classification.',
    weightage_percentage: 13,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dbms-6',
    subject_id: 'sub-dbms',
    unit_number: 6,
    title: 'NoSQL Databases & Distributed Systems',
    description: 'CAP Theorem, MongoDB vs SQL, Key-Value stores, Document stores, BASE properties.',
    weightage_percentage: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // DSA Units (sub-dsa)
  {
    id: 'unit-dsa-1',
    subject_id: 'sub-dsa',
    unit_number: 1,
    title: 'Linear Data Structures: Stacks and Queues',
    description: 'Array and linked representations, infix-postfix conversions, circular queues, deques.',
    weightage_percentage: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dsa-2',
    subject_id: 'sub-dsa',
    unit_number: 2,
    title: 'Trees and Binary Search Trees',
    description: 'Binary trees, traversal algorithms, BST operations, expression trees, threaded binary trees.',
    weightage_percentage: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dsa-3',
    subject_id: 'sub-dsa',
    unit_number: 3,
    title: 'Advanced Balanced Trees & Heaps',
    description: 'AVL tree rotations, Red-Black trees, B-Trees, B+ Trees, Min/Max binary heaps, Priority queues.',
    weightage_percentage: 20,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dsa-4',
    subject_id: 'sub-dsa',
    unit_number: 4,
    title: 'Graph Algorithms & Applications',
    description: 'Graph representations, BFS, DFS, Dijkstra shortest path, Prim and Kruskal MST algorithms.',
    weightage_percentage: 20,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dsa-5',
    subject_id: 'sub-dsa',
    unit_number: 5,
    title: 'Hashing and Collision Resolution',
    description: 'Hash functions, Linear Probing, Quadratic Probing, Double Hashing, Separate Chaining.',
    weightage_percentage: 14,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-dsa-6',
    subject_id: 'sub-dsa',
    unit_number: 6,
    title: 'File Organization and External Sorting',
    description: 'Sequential, index sequential, direct access files, external merge sort, multi-way merging.',
    weightage_percentage: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OOP Units (sub-oop)
  {
    id: 'unit-oop-1',
    subject_id: 'sub-oop',
    unit_number: 1,
    title: 'Fundamentals of Object Oriented Programming',
    description: 'Paradigm principles, Encapsulation, Abstraction, Inheritance, Polymorphism, class structures.',
    weightage_percentage: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-oop-2',
    subject_id: 'sub-oop',
    unit_number: 2,
    title: 'Classes, Objects, and Constructors',
    description: 'Dynamic memory allocation, constructors, destructors, copy constructors, static members, friend functions.',
    weightage_percentage: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-oop-3',
    subject_id: 'sub-oop',
    unit_number: 3,
    title: 'Inheritance and Polymorphism',
    description: 'Single, multiple, multilevel inheritance, virtual base classes, virtual functions, pure virtual functions.',
    weightage_percentage: 22,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-oop-4',
    subject_id: 'sub-oop',
    unit_number: 4,
    title: 'Operator Overloading and Type Conversions',
    description: 'Unary and binary operator overloading, member function vs friend function overloading, data conversions.',
    weightage_percentage: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-oop-5',
    subject_id: 'sub-oop',
    unit_number: 5,
    title: 'Templates and Exception Handling',
    description: 'Function templates, class templates, try-catch-throw mechanisms, multiple catch blocks, rethrowing.',
    weightage_percentage: 14,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-oop-6',
    subject_id: 'sub-oop',
    unit_number: 6,
    title: 'File Streams & Standard Template Library (STL)',
    description: 'File input/output streams, file pointers, error handling, STL vectors, lists, maps, iterators.',
    weightage_percentage: 14,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OS Units (sub-os)
  {
    id: 'unit-os-1',
    subject_id: 'sub-os',
    unit_number: 1,
    title: 'Introduction to Operating Systems & Architecture',
    description: 'OS services, Dual-mode operation, System calls, OS structures (monolithic, microkernel), booting.',
    weightage_percentage: 14,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-os-2',
    subject_id: 'sub-os',
    unit_number: 2,
    title: 'Process Management and CPU Scheduling',
    description: 'Process states, PCB, Context switching, FCFS, SJF, Priority, Round Robin scheduling algorithms.',
    weightage_percentage: 20,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-os-3',
    subject_id: 'sub-os',
    unit_number: 3,
    title: 'Process Synchronization & Deadlocks',
    description: 'Critical Section problem, Peterson solution, Semaphores, Mutex, Banker algorithm, Deadlock prevention.',
    weightage_percentage: 22,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-os-4',
    subject_id: 'sub-os',
    unit_number: 4,
    title: 'Memory Management Systems',
    description: 'Logical vs physical addresses, Contiguous allocation, Paging, Segmentation, TLB hardware.',
    weightage_percentage: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-os-5',
    subject_id: 'sub-os',
    unit_number: 5,
    title: 'Virtual Memory & Page Replacement',
    description: 'Demand paging, Page fault handling, Page replacement algorithms: FIFO, LRU, Optimal, Thrashing.',
    weightage_percentage: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-os-6',
    subject_id: 'sub-os',
    unit_number: 6,
    title: 'Storage & File System Management',
    description: 'File concepts, Directory structure, Disk scheduling (FCFS, SSTF, SCAN, C-SCAN), Free space management.',
    weightage_percentage: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // TOC Units (sub-toc)
  {
    id: 'unit-toc-1',
    subject_id: 'sub-toc',
    unit_number: 1,
    title: 'Finite Automata and Formal Languages',
    description: 'Alphabets, strings, DFA, NFA, epsilon-NFA, NFA to DFA conversion, minimization of DFA.',
    weightage_percentage: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-toc-2',
    subject_id: 'sub-toc',
    unit_number: 2,
    title: 'Regular Expressions & Pumping Lemma',
    description: 'Regular expressions, Arden Theorem, Equivalence of RE and FA, Pumping Lemma for regular sets.',
    weightage_percentage: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-toc-3',
    subject_id: 'sub-toc',
    unit_number: 3,
    title: 'Context-Free Grammars & Pushdown Automata',
    description: 'CFG definition, Derivation trees, Ambiguity, Pushdown Automata (DPDA, NPDA), Acceptance mechanisms.',
    weightage_percentage: 22,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-toc-4',
    subject_id: 'sub-toc',
    unit_number: 4,
    title: 'Context-Free Languages & Normal Forms',
    description: 'Chomsky Normal Form (CNF), Greibach Normal Form (GNF), Pumping Lemma for CFLs, Closure properties.',
    weightage_percentage: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-toc-5',
    subject_id: 'sub-toc',
    unit_number: 5,
    title: 'Turing Machines and Computability',
    description: 'Standard Turing Machine, Instantaneous Descriptions, Design of TMs for language recognition and arithmetic.',
    weightage_percentage: 16,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'unit-toc-6',
    subject_id: 'sub-toc',
    unit_number: 6,
    title: 'Decidability & Computational Complexity',
    description: 'Decidable vs Undecidable problems, Universal Turing Machine, Halting Problem, Post Correspondence Problem, P vs NP.',
    weightage_percentage: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_TOPICS: Topic[] = [
  // DBMS Topics
  {
    id: 'topic-dbms-er',
    unit_id: 'unit-dbms-1',
    title: 'Entity Relationship Modeling & Constraints',
    description: 'Entities, attributes, relationships, cardinality, participation constraints, and ER-to-relational schema mapping.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-dbms-ra',
    unit_id: 'unit-dbms-2',
    title: 'Relational Algebra Operations',
    description: 'Select, project, Cartesian product, set difference, natural join, outer joins, and division operator.',
    order_index: 1,
    importance_level: 'HIGH',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-norm-3nf',
    unit_id: 'unit-dbms-3',
    title: '3NF and BCNF Normalization',
    description: 'Comparison of 3NF and BCNF, functional dependencies, loss-free decomposition algorithms, and canonical cover.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-trans-acid',
    unit_id: 'unit-dbms-4',
    title: 'ACID Properties and Serializability',
    description: 'Atomicity, Consistency, Isolation, Durability, conflict serializability testing using precedence graphs.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-concur-2pl',
    unit_id: 'unit-dbms-4',
    title: 'Two-Phase Locking (2PL) Protocol',
    description: 'Growing phase, shrinking phase, strict 2PL, rigorous 2PL, and deadlock handling strategies.',
    order_index: 2,
    importance_level: 'HIGH',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-dbms-recovery',
    unit_id: 'unit-dbms-5',
    title: 'Log-Based Recovery & Checkpointing',
    description: 'Deferred database modification, immediate modification, checkpointing procedure, and ARIES phases.',
    order_index: 1,
    importance_level: 'HIGH',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // DSA Topics
  {
    id: 'topic-dsa-stack-queue',
    unit_id: 'unit-dsa-1',
    title: 'Stack Applications & Circular Queues',
    description: 'Infix to postfix conversion, postfix evaluation, circular queue boundary conditions.',
    order_index: 1,
    importance_level: 'HIGH',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-dsa-bst',
    unit_id: 'unit-dsa-2',
    title: 'Binary Search Tree Algorithms',
    description: 'Recursive insertion, deletion with 2 children cases, in-order, pre-order, post-order traversals.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-dsa-avl',
    unit_id: 'unit-dsa-3',
    title: 'AVL Tree Balancing & Rotations',
    description: 'Balance factor computation, LL, RR, LR, RL single and double rotation techniques.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-dsa-graph-dijkstra',
    unit_id: 'unit-dsa-4',
    title: 'Shortest Paths & Minimum Spanning Trees',
    description: 'Dijkstra single source shortest path, Prim and Kruskal greedy algorithms with cut property.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OOP Topics
  {
    id: 'topic-oop-poly',
    unit_id: 'unit-oop-3',
    title: 'Virtual Functions & Runtime Polymorphism',
    description: 'VTABLE, VPTR mechanisms, pure virtual functions, and abstract class implementations.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-oop-op-overload',
    unit_id: 'unit-oop-4',
    title: 'Operator Overloading Rules & Syntax',
    description: 'Overloading +, -, == operators, stream insertion (<<) and extraction (>>) operators via friend functions.',
    order_index: 1,
    importance_level: 'HIGH',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OS Topics
  {
    id: 'topic-os-sched',
    unit_id: 'unit-os-2',
    title: 'CPU Scheduling Algorithms',
    description: 'Gantt chart construction, waiting time, turnaround time for FCFS, Non-preemptive/Preemptive SJF, Round Robin.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-os-deadlock',
    unit_id: 'unit-os-3',
    title: 'Banker Algorithm & Deadlock Prevention',
    description: 'Coffman four conditions, safety algorithm, resource request algorithm, resource allocation graph.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-os-page-rep',
    unit_id: 'unit-os-5',
    title: 'Page Replacement Algorithms (FIFO, LRU, Optimal)',
    description: 'Reference string trace, page fault ratio calculation, Belady anomaly demonstration.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // TOC Topics
  {
    id: 'topic-toc-dfa',
    unit_id: 'unit-toc-1',
    title: 'DFA Construction & NFA Equivalence',
    description: 'State transition diagrams, subset construction algorithm, DFA state minimization using table filling.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-toc-pumping',
    unit_id: 'unit-toc-2',
    title: 'Pumping Lemma for Regular Languages',
    description: 'Adversary game proof technique to prove non-regularity of languages like a^n b^n.',
    order_index: 1,
    importance_level: 'HIGH',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-toc-cnf',
    unit_id: 'unit-toc-4',
    title: 'Chomsky Normal Form (CNF) Conversion',
    description: 'Elimination of epsilon productions, unit productions, useless symbols, and final binary conversion steps.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'topic-toc-tm',
    unit_id: 'unit-toc-5',
    title: 'Turing Machine Construction for Language Recognition',
    description: 'Formal definition, transition function table, state diagram for languages a^n b^n c^n, palindrome.',
    order_index: 1,
    importance_level: 'MUST_STUDY',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_SYLLABUS_ITEMS: SyllabusItem[] = [
  // DBMS Syllabus
  {
    id: 'syl-dbms-1',
    unit_id: 'unit-dbms-1',
    topic_id: 'topic-dbms-er',
    content: 'Database System Applications, Purpose of Database Systems, View of Data, Database Languages, Relational Databases, Database Design, Data Storage and Querying, Transaction Management, Database Architecture. Entity-Relationship Model: Basic concepts, Constraints, Design Issues, Weak Entity Sets, Extended E-R Features.',
    reference_materials: 'Silberschatz, Korth, Sudarshan - Database System Concepts (6th Edition), McGraw-Hill (Chapters 1, 2, 7)',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'syl-dbms-2',
    unit_id: 'unit-dbms-2',
    topic_id: 'topic-dbms-ra',
    content: 'Structure of Relational Databases, Fundamental Relational-Algebra Operations (Select, Project, Union, Set Difference, Cartesian Product, Rename), Additional Relational-Algebra Operations, Extended Relational-Algebra Operations. SQL: Background, SQL Data Definition, Basic Structure of SQL Queries, Set Operations, Aggregate Functions, Null Values, Nested Subqueries.',
    reference_materials: 'Silberschatz, Korth, Sudarshan - Database System Concepts, McGraw-Hill (Chapters 3, 4, 6)',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'syl-dbms-3',
    unit_id: 'unit-dbms-3',
    topic_id: 'topic-norm-3nf',
    content: 'Features of Good Relational Designs, Atomic Domains and First Normal Form, Decomposition Using Functional Dependencies (Functional Dependency Theory, Algorithms for Functional Dependencies, Decomposition using 3NF and BCNF). Lossless-Join Decomposition, Dependency Preservation.',
    reference_materials: 'Silberschatz, Korth, Sudarshan - Database System Concepts (Chapter 8); Elmasri & Navathe - Fundamentals of Database Systems',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'syl-dbms-4',
    unit_id: 'unit-dbms-4',
    topic_id: 'topic-trans-acid',
    content: 'Transaction Concept, Transaction State, Implementation of Atomicity and Durability, Concurrent Executions, Serializability, Recoverability, Implementation of Isolation. Concurrency Control: Lock-Based Protocols, Timestamp-Based Protocols, Validation-Based Protocols, Multiple Granularity, Deadlock Handling.',
    reference_materials: 'Silberschatz, Korth, Sudarshan - Database System Concepts (Chapters 14, 15)',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // DSA Syllabus
  {
    id: 'syl-dsa-1',
    unit_id: 'unit-dsa-1',
    topic_id: 'topic-dsa-stack-queue',
    content: 'Stack: Basic concepts, Operations, Implementation using arrays and linked lists, Applications of Stacks (Infix to Postfix conversion, Evaluation of postfix expression). Queue: Operations, Array and Linked list representation, Circular Queue, Deque, Priority Queue concepts.',
    reference_materials: 'Horowitz, Sahni, Anderson-Freed - Fundamentals of Data Structures in C (2nd Edition)',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'syl-dsa-2',
    unit_id: 'unit-dsa-2',
    topic_id: 'topic-dsa-bst',
    content: 'Trees: Basic terminology, Binary Tree representation, Binary Tree traversals (Inorder, Preorder, Postorder - recursive and non-recursive), Expression Trees. Binary Search Tree (BST): Definition, Operations (Search, Insert, Delete), Threaded Binary Trees.',
    reference_materials: 'Horowitz, Sahni; Cormen, Leiserson, Rivest, Stein - Introduction to Algorithms (CLRS)',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'syl-dsa-3',
    unit_id: 'unit-dsa-3',
    topic_id: 'topic-dsa-avl',
    content: 'Balanced Trees: AVL Tree, Rotations (LL, RR, LR, RL), Height balancing in AVL trees, Insertion and Deletion in AVL trees. B-Trees, B+ Trees: Definitions, Searching, Insertion, and Deletion concepts. Heaps: Min-heap, Max-heap, Heap Sort.',
    reference_materials: 'Mark Allen Weiss - Data Structures and Algorithm Analysis in C++ (4th Edition)',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'syl-dsa-4',
    unit_id: 'unit-dsa-4',
    topic_id: 'topic-dsa-graph-dijkstra',
    content: 'Graphs: Terminology, Representation (Adjacency matrix, Adjacency list), Graph traversals: Depth First Search (DFS), Breadth First Search (BFS). Minimum Spanning Trees: Prim algorithm, Kruskal algorithm. Shortest Path algorithms: Dijkstra algorithm.',
    reference_materials: 'Cormen, Leiserson, Rivest, Stein - Introduction to Algorithms (Chapters 22, 23, 24)',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OOP Syllabus
  {
    id: 'syl-oop-1',
    unit_id: 'unit-oop-3',
    topic_id: 'topic-oop-poly',
    content: 'Polymorphism: Compile time polymorphism vs Run time polymorphism. Pointers to derived classes, Virtual Functions, Pure Virtual Functions, Abstract Classes, Virtual Destructors, Early Binding vs Late Binding, Mechanism of Virtual Table (vptr and vtable).',
    reference_materials: 'E. Balagurusamy - Object Oriented Programming with C++; Bjarne Stroustrup - The C++ Programming Language',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OS Syllabus
  {
    id: 'syl-os-1',
    unit_id: 'unit-os-2',
    topic_id: 'topic-os-sched',
    content: 'Process Management: Process Concept, Process Scheduling, Operations on Processes, Interprocess Communication. CPU Scheduling: Basic Concepts, Scheduling Criteria, Scheduling Algorithms: First-Come, First-Served (FCFS), Shortest-Job-First (SJF), Priority Scheduling, Round-Robin (RR), Multilevel Queue Scheduling.',
    reference_materials: 'Silberschatz, Galvin, Gagne - Operating System Concepts (9th Edition), Wiley (Chapters 3, 5)',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'syl-os-2',
    unit_id: 'unit-os-3',
    topic_id: 'topic-os-deadlock',
    content: 'Deadlocks: System Model, Deadlock Characterization (Necessary conditions, Resource Allocation Graph), Methods for Handling Deadlocks, Deadlock Prevention, Deadlock Avoidance (Banker Algorithm), Deadlock Detection and Recovery.',
    reference_materials: 'Silberschatz, Galvin, Gagne - Operating System Concepts (Chapter 7)',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // TOC Syllabus
  {
    id: 'syl-toc-1',
    unit_id: 'unit-toc-1',
    topic_id: 'topic-toc-dfa',
    content: 'Introduction to Theory of Computation: Alphabets, Strings, Languages. Finite Automata: Deterministic Finite Automata (DFA), Non-deterministic Finite Automata (NFA), Equivalence of DFA and NFA, NFA with epsilon-transitions, Conversion of NFA to DFA, Minimization of DFA.',
    reference_materials: 'Hopcroft, Motwani, Ullman - Introduction to Automata Theory, Languages, and Computation (3rd Edition), Pearson',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'syl-toc-2',
    unit_id: 'unit-toc-5',
    topic_id: 'topic-toc-tm',
    content: 'Turing Machines: Formal Definition of Turing Machine, Instantaneous Descriptions, Design of Turing Machines for Language Recognition and Computation of Functions, Techniques for TM construction, Variations of Turing Machines.',
    reference_materials: 'Peter Linz - An Introduction to Formal Languages and Automata (6th Edition); Hopcroft & Ullman',
    hours_allocated: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_CONTENT_SOURCES: ContentSource[] = [
  {
    id: 'src-official-sppu',
    name: 'SPPU Board of Studies in Computer Engineering',
    source_type: 'OFFICIAL',
    source_url: 'http://www.unipune.ac.in/syllabi/',
    license_type: 'Official University Curriculum & Past Papers',
    copyright_notes: 'Public educational examination documents used for academic reference.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_QUESTIONS: Question[] = [
  // DBMS Verified Questions
  {
    id: 'q-dbms-3nf-bcnf',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-3',
    topic_id: 'topic-norm-3nf',
    question_text: 'Explain 3NF and BCNF with a suitable example. Differentiate between 3NF and BCNF.',
    normalized_question: 'explain 3nf and bcnf with example and differentiate between them',
    marks: 8,
    difficulty: 'MEDIUM',
    question_type: 'THEORY',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-dbms-acid',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-4',
    topic_id: 'topic-trans-acid',
    question_text: 'What are ACID properties of a transaction? Explain how the DBMS enforces Atomicity and Durability.',
    normalized_question: 'what are acid properties of transaction and how dbms enforces atomicity and durability',
    marks: 7,
    difficulty: 'EASY',
    question_type: 'THEORY',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-dbms-2pl',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-4',
    topic_id: 'topic-concur-2pl',
    question_text: 'Explain Two-Phase Locking (2PL) protocol. What are strict 2PL and rigorous 2PL?',
    normalized_question: 'explain two phase locking 2pl protocol strict and rigorous 2pl',
    marks: 6,
    difficulty: 'MEDIUM',
    question_type: 'THEORY',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-dbms-er-diag',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-1',
    topic_id: 'topic-dbms-er',
    question_text: 'Design an ER diagram for a Hospital Management System. Clearly state all entity sets, relationships, key constraints, and mapping cardinalities.',
    normalized_question: 'design er diagram for hospital management system with constraints and keys',
    marks: 10,
    difficulty: 'HARD',
    question_type: 'DIAGRAM',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-dbms-ra-ops',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-2',
    topic_id: 'topic-dbms-ra',
    question_text: 'Define Relational Algebra. Explain the fundamental operators (Select, Project, Union, Set Difference, Cartesian Product) with formal expressions.',
    normalized_question: 'define relational algebra and fundamental operators with expressions',
    marks: 6,
    difficulty: 'MEDIUM',
    question_type: 'THEORY',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-dbms-def-trans',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-4',
    topic_id: 'topic-trans-acid',
    question_text: 'Define Transaction in DBMS. List the four properties every transaction must satisfy.',
    normalized_question: 'define transaction in dbms list four properties',
    marks: 2,
    difficulty: 'EASY',
    question_type: 'SHORT_ANSWER',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // DSA Verified Questions
  {
    id: 'q-dsa-avl',
    subject_id: 'sub-dsa',
    unit_id: 'unit-dsa-3',
    topic_id: 'topic-dsa-avl',
    question_text: 'What is an AVL Tree? Explain LL, RR, LR, and RL rotations with examples.',
    normalized_question: 'what is avl tree explain ll rr lr rl rotations with examples',
    marks: 10,
    difficulty: 'HARD',
    question_type: 'DIAGRAM',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-dsa-dijkstra',
    subject_id: 'sub-dsa',
    unit_id: 'unit-dsa-4',
    topic_id: 'topic-dsa-graph-dijkstra',
    question_text: 'Write Dijkstra algorithm for single-source shortest path. Trace the algorithm on a given directed weighted graph starting from vertex A.',
    normalized_question: 'write dijkstra algorithm for shortest path and trace on directed graph',
    marks: 8,
    difficulty: 'MEDIUM',
    question_type: 'NUMERICAL',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-dsa-bst-delete',
    subject_id: 'sub-dsa',
    unit_id: 'unit-dsa-2',
    topic_id: 'topic-dsa-bst',
    question_text: 'Explain the node deletion algorithm in a Binary Search Tree (BST) covering all three cases (leaf node, one child, two children).',
    normalized_question: 'explain node deletion algorithm in binary search tree three cases',
    marks: 6,
    difficulty: 'MEDIUM',
    question_type: 'THEORY',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-dsa-circ-queue',
    subject_id: 'sub-dsa',
    unit_id: 'unit-dsa-1',
    topic_id: 'topic-dsa-stack-queue',
    question_text: 'Why is a circular queue preferred over a linear queue? Write algorithms for enqueue and dequeue in a circular queue.',
    normalized_question: 'why circular queue preferred over linear queue write enqueue and dequeue',
    marks: 5,
    difficulty: 'EASY',
    question_type: 'THEORY',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-dsa-def-tree',
    subject_id: 'sub-dsa',
    unit_id: 'unit-dsa-2',
    topic_id: 'topic-dsa-bst',
    question_text: 'Define balance factor of a node in an AVL tree.',
    normalized_question: 'define balance factor of node in avl tree',
    marks: 2,
    difficulty: 'EASY',
    question_type: 'SHORT_ANSWER',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OOP Verified Questions
  {
    id: 'q-oop-virtual',
    subject_id: 'sub-oop',
    unit_id: 'unit-oop-3',
    topic_id: 'topic-oop-poly',
    question_text: 'Explain the concept of Virtual Functions and Pure Virtual Functions in C++. How does runtime polymorphism work using vptr and vtable?',
    normalized_question: 'explain virtual functions pure virtual functions c++ vptr and vtable',
    marks: 8,
    difficulty: 'MEDIUM',
    question_type: 'THEORY',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-oop-op-plus',
    subject_id: 'sub-oop',
    unit_id: 'unit-oop-4',
    topic_id: 'topic-oop-op-overload',
    question_text: 'Write a complete C++ program to overload the binary addition operator (+) using a friend function to add two Complex numbers.',
    normalized_question: 'write c++ program to overload binary addition operator friend function complex numbers',
    marks: 6,
    difficulty: 'MEDIUM',
    question_type: 'NUMERICAL',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-oop-def-abstract',
    subject_id: 'sub-oop',
    unit_id: 'unit-oop-3',
    topic_id: 'topic-oop-poly',
    question_text: 'What is an Abstract Class in C++? Can an object of an abstract class be instantiated?',
    normalized_question: 'what is abstract class in c++ can object be instantiated',
    marks: 2,
    difficulty: 'EASY',
    question_type: 'SHORT_ANSWER',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OS Verified Questions
  {
    id: 'q-os-sched-num',
    subject_id: 'sub-os',
    unit_id: 'unit-os-2',
    topic_id: 'topic-os-sched',
    question_text: 'Consider four processes P1, P2, P3, P4 with given burst times and arrival times. Draw the Gantt chart and compute average waiting time and turnaround time for Round Robin (Time Quantum = 2ms).',
    normalized_question: 'consider four processes burst times arrival times round robin gantt chart waiting time',
    marks: 8,
    difficulty: 'MEDIUM',
    question_type: 'NUMERICAL',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-os-banker',
    subject_id: 'sub-os',
    unit_id: 'unit-os-3',
    topic_id: 'topic-os-deadlock',
    question_text: 'Explain the Banker Algorithm for Deadlock Avoidance. State the safety algorithm steps and resource request evaluation procedure.',
    normalized_question: 'explain banker algorithm deadlock avoidance safety algorithm resource request',
    marks: 8,
    difficulty: 'HARD',
    question_type: 'THEORY',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-os-lru-rep',
    subject_id: 'sub-os',
    unit_id: 'unit-os-5',
    topic_id: 'topic-os-page-rep',
    question_text: 'Given the page reference string: 7, 0, 1, 2, 0, 3, 0, 4, 2, 3, 0, 3, 2, 1, 2, 0, 1, 7, 0, 1 with 3 memory frames, calculate the number of page faults using LRU page replacement algorithm.',
    normalized_question: 'given page reference string calculate page faults lru page replacement 3 frames',
    marks: 6,
    difficulty: 'MEDIUM',
    question_type: 'NUMERICAL',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-os-def-deadlock',
    subject_id: 'sub-os',
    unit_id: 'unit-os-3',
    topic_id: 'topic-os-deadlock',
    question_text: 'State the four Coffman conditions necessary for a deadlock to occur.',
    normalized_question: 'state four coffman conditions necessary for deadlock to occur',
    marks: 2,
    difficulty: 'EASY',
    question_type: 'SHORT_ANSWER',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // TOC Verified Questions
  {
    id: 'q-toc-dfa-design',
    subject_id: 'sub-toc',
    unit_id: 'unit-toc-1',
    topic_id: 'topic-toc-dfa',
    question_text: 'Design a DFA over alphabet {0, 1} that accepts all binary strings ending with substring "101". Draw the state transition table and transition diagram.',
    normalized_question: 'design dfa over alphabet 0 1 accepting strings ending with 101 state transition table',
    marks: 6,
    difficulty: 'MEDIUM',
    question_type: 'DIAGRAM',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-toc-pumping-lemma',
    subject_id: 'sub-toc',
    unit_id: 'unit-toc-2',
    topic_id: 'topic-toc-pumping',
    question_text: 'State and prove the Pumping Lemma for Regular Languages. Using it, prove that language L = {a^n b^n | n >= 0} is not regular.',
    normalized_question: 'state prove pumping lemma regular languages prove an bn not regular',
    marks: 8,
    difficulty: 'HARD',
    question_type: 'THEORY',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-toc-tm-design',
    subject_id: 'sub-toc',
    unit_id: 'unit-toc-5',
    topic_id: 'topic-toc-tm',
    question_text: 'Design a standard Turing Machine to accept the language L = {a^n b^n c^n | n >= 1}. Give the complete state transition diagram and instantaneous description trace for "aabbcc".',
    normalized_question: 'design turing machine accept an bn cn transition diagram trace aabbcc',
    marks: 10,
    difficulty: 'HARD',
    question_type: 'DIAGRAM',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'q-toc-def-alphabet',
    subject_id: 'sub-toc',
    unit_id: 'unit-toc-1',
    topic_id: 'topic-toc-dfa',
    question_text: 'Define Alphabet (Σ) and Language (L) in Theory of Computation with examples.',
    normalized_question: 'define alphabet and language in theory of computation with examples',
    marks: 2,
    difficulty: 'EASY',
    question_type: 'SHORT_ANSWER',
    is_pyq: true,
    verification_status: 'VERIFIED',
    content_status: 'PUBLISHED',
    source_id: 'src-official-sppu',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_QUESTION_OCCURRENCES: QuestionOccurrence[] = [
  // DBMS Occurrences
  {
    id: 'occ-1',
    question_id: 'q-dbms-3nf-bcnf',
    year: 2024,
    exam_session: 'IN_SEM',
    question_number: 'Q3(a)',
    marks: 8,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-2',
    question_id: 'q-dbms-3nf-bcnf',
    year: 2023,
    exam_session: 'END_SEM',
    question_number: 'Q4(b)',
    marks: 8,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-2b',
    question_id: 'q-dbms-3nf-bcnf',
    year: 2023,
    exam_session: 'IN_SEM',
    question_number: 'Q3(a)',
    marks: 8,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-2c',
    question_id: 'q-dbms-3nf-bcnf',
    year: 2022,
    exam_session: 'END_SEM',
    question_number: 'Q4(a)',
    marks: 8,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-3',
    question_id: 'q-dbms-acid',
    year: 2024,
    exam_session: 'END_SEM',
    question_number: 'Q5(a)',
    marks: 7,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-4',
    question_id: 'q-dbms-acid',
    year: 2023,
    exam_session: 'IN_SEM',
    question_number: 'Q2(b)',
    marks: 6,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-4b',
    question_id: 'q-dbms-acid',
    year: 2022,
    exam_session: 'END_SEM',
    question_number: 'Q5(b)',
    marks: 7,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-5',
    question_id: 'q-dbms-2pl',
    year: 2024,
    exam_session: 'END_SEM',
    question_number: 'Q6(a)',
    marks: 6,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-6',
    question_id: 'q-dbms-er-diag',
    year: 2024,
    exam_session: 'IN_SEM',
    question_number: 'Q1(a)',
    marks: 10,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-7',
    question_id: 'q-dbms-ra-ops',
    year: 2023,
    exam_session: 'IN_SEM',
    question_number: 'Q2(a)',
    marks: 6,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-8',
    question_id: 'q-dbms-def-trans',
    year: 2024,
    exam_session: 'IN_SEM',
    question_number: 'Q1(c)',
    marks: 2,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dbms',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // DSA Occurrences
  {
    id: 'occ-9',
    question_id: 'q-dsa-avl',
    year: 2024,
    exam_session: 'END_SEM',
    question_number: 'Q3(a)',
    marks: 10,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dsa',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-10',
    question_id: 'q-dsa-dijkstra',
    year: 2024,
    exam_session: 'END_SEM',
    question_number: 'Q5(a)',
    marks: 8,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dsa',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-11',
    question_id: 'q-dsa-bst-delete',
    year: 2023,
    exam_session: 'IN_SEM',
    question_number: 'Q2(a)',
    marks: 6,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dsa',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-12',
    question_id: 'q-dsa-circ-queue',
    year: 2024,
    exam_session: 'IN_SEM',
    question_number: 'Q1(a)',
    marks: 5,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dsa',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-13',
    question_id: 'q-dsa-def-tree',
    year: 2024,
    exam_session: 'IN_SEM',
    question_number: 'Q1(c)',
    marks: 2,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-dsa',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OOP Occurrences
  {
    id: 'occ-14',
    question_id: 'q-oop-virtual',
    year: 2024,
    exam_session: 'END_SEM',
    question_number: 'Q4(a)',
    marks: 8,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-oop',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-15',
    question_id: 'q-oop-op-plus',
    year: 2024,
    exam_session: 'END_SEM',
    question_number: 'Q6(a)',
    marks: 6,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-oop',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-16',
    question_id: 'q-oop-def-abstract',
    year: 2023,
    exam_session: 'IN_SEM',
    question_number: 'Q1(b)',
    marks: 2,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-3',
    subject_id: 'sub-oop',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // OS Occurrences
  {
    id: 'occ-17',
    question_id: 'q-os-sched-num',
    year: 2024,
    exam_session: 'IN_SEM',
    question_number: 'Q2(a)',
    marks: 8,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    subject_id: 'sub-os',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-18',
    question_id: 'q-os-banker',
    year: 2024,
    exam_session: 'END_SEM',
    question_number: 'Q3(a)',
    marks: 8,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    subject_id: 'sub-os',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-19',
    question_id: 'q-os-lru-rep',
    year: 2023,
    exam_session: 'END_SEM',
    question_number: 'Q5(a)',
    marks: 6,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    subject_id: 'sub-os',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-20',
    question_id: 'q-os-def-deadlock',
    year: 2024,
    exam_session: 'IN_SEM',
    question_number: 'Q1(a)',
    marks: 2,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    subject_id: 'sub-os',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // TOC Occurrences
  {
    id: 'occ-21',
    question_id: 'q-toc-dfa-design',
    year: 2024,
    exam_session: 'IN_SEM',
    question_number: 'Q1(a)',
    marks: 6,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    subject_id: 'sub-toc',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-22',
    question_id: 'q-toc-pumping-lemma',
    year: 2024,
    exam_session: 'IN_SEM',
    question_number: 'Q2(a)',
    marks: 8,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    subject_id: 'sub-toc',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-23',
    question_id: 'q-toc-tm-design',
    year: 2024,
    exam_session: 'END_SEM',
    question_number: 'Q6(a)',
    marks: 10,
    pattern_id: 'pat-2024',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    subject_id: 'sub-toc',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'occ-24',
    question_id: 'q-toc-def-alphabet',
    year: 2023,
    exam_session: 'IN_SEM',
    question_number: 'Q1(c)',
    marks: 2,
    pattern_id: 'pat-2019',
    branch_id: 'branch-comp',
    semester_id: 'sem-4',
    subject_id: 'sub-toc',
    source_id: 'src-official-sppu',
    verification_status: 'VERIFIED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_QUESTION_CLUSTERS: QuestionCluster[] = [
  {
    id: 'cluster-norm',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-3',
    topic_id: 'topic-norm-3nf',
    canonical_name: 'Normalization (1NF, 2NF, 3NF, BCNF)',
    canonical_question: 'Explain 3NF and BCNF with suitable examples and loss-free decomposition.',
    occurrence_count: 4,
    years: [2025, 2024, 2023, 2022],
    typical_marks: '5–10 Marks',
    confidence_score: 0.96,
    human_approved: true,
    review_status: 'APPROVED',
    repetition_summary: 'Repeated/Similar in 4 verified papers',
    clustering_algorithm: 'HYBRID',
    embedding_model: null,
    approved_by: 'usr-admin-1',
    approved_at: new Date().toISOString(),
    trend: 'HIGH',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cluster-acid',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-4',
    topic_id: 'topic-trans-acid',
    canonical_name: 'ACID Properties & Serializability',
    canonical_question: 'Describe ACID properties of transaction and conflict serializability testing.',
    occurrence_count: 3,
    years: [2024, 2023, 2022],
    typical_marks: '6–7 Marks',
    confidence_score: 0.94,
    human_approved: true,
    review_status: 'APPROVED',
    repetition_summary: 'Repeated/Similar in 3 verified papers',
    clustering_algorithm: 'HYBRID',
    embedding_model: null,
    approved_by: 'usr-admin-1',
    approved_at: new Date().toISOString(),
    trend: 'HIGH',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_CLUSTER_MEMBERS: QuestionClusterMember[] = [
  {
    id: 'mem-1',
    cluster_id: 'cluster-norm',
    question_id: 'q-dbms-3nf-bcnf',
    repetition_type: 'EXACT_REPETITION',
    similarity_score: 0.98,
    confidence_level: 'VERY_HIGH',
    match_explanation: 'Standard verified question on 3NF and BCNF.',
    added_by: 'usr-admin-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mem-2',
    cluster_id: 'cluster-acid',
    question_id: 'q-dbms-acid',
    repetition_type: 'EXACT_REPETITION',
    similarity_score: 0.96,
    confidence_level: 'VERY_HIGH',
    match_explanation: 'Core ACID properties question.',
    added_by: 'usr-admin-1',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mem-3',
    cluster_id: 'cluster-acid',
    question_id: 'q-dbms-def-trans',
    repetition_type: 'CONCEPT_REPETITION',
    similarity_score: 0.85,
    confidence_level: 'HIGH',
    match_explanation: 'Transaction properties concept overlap.',
    added_by: 'usr-admin-1',
    created_at: new Date().toISOString(),
  },
];

export const SEED_ANSWERS: Answer[] = [
  {
    id: 'ans-1',
    question_id: 'q-dbms-3nf-bcnf',
    marks_target: 5,
    heading: '5-Mark Concise Answer: 3NF vs BCNF',
    summary: '3NF permits non-prime attributes to depend on candidate keys, whereas BCNF strictly requires every determinant X in X → Y to be a superkey.',
    key_points: [
      '3NF condition: For every X → Y, either X is a superkey OR Y is a prime attribute.',
      'BCNF condition: For every non-trivial X → Y, X MUST strictly be a superkey.',
      'Strictness: All BCNF relations are in 3NF, but not all 3NF relations satisfy BCNF.',
      'Dependency Preservation: 3NF always guarantees dependency preservation; BCNF may not.',
    ],
    diagram_description: 'Venn diagram depicting 1NF ⊃ 2NF ⊃ 3NF ⊃ BCNF hierarchy.',
    example_text: 'Relation R(Student_ID, Course, Advisor) with (Student_ID, Course) → Advisor and Advisor → Course.',
    evaluator_tips: 'State formal definitions first. Draw the nested circle diagram to secure maximum presentation marks.',
    is_premium: false,
    content_status: 'PUBLISHED',
    author_id: 'usr-admin-1',
    verified_by: 'usr-admin-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ans-2',
    question_id: 'q-dbms-3nf-bcnf',
    marks_target: 10,
    heading: '10-Mark Detailed Answer with Decomposition Walkthrough',
    summary: 'Full step-by-step breakdown including Functional Dependency analysis, candidate key evaluation, and loss-free BCNF decomposition step by step.',
    key_points: [
      'Formal mathematical definitions of Prime and Non-Prime attributes.',
      'Candidate key identification using attribute closure method.',
      'Step-by-step example with table schemas and loss-less join proof.',
      'Comparison matrix covering Redundancy, Anomalies, and Dependency Preservation.',
    ],
    diagram_description: 'Step-by-step schema decomposition tree showing R decomposed into R1 and R2.',
    evaluator_tips: 'Must include attribute closure calculation (X+) to demonstrate candidate key identification.',
    is_premium: true,
    content_status: 'PUBLISHED',
    author_id: 'usr-admin-1',
    verified_by: 'usr-admin-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_NOTES: Note[] = [
  {
    id: 'note-norm',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-3',
    topic_id: 'topic-norm-3nf',
    title: 'Complete Exam Guide to Database Normalization',
    slug: 'database-normalization-guide',
    summary: 'Comprehensive high-yield notes covering Functional Dependencies, 1NF through BCNF, and lossless join decomposition.',
    content_body: `# Database Normalization

## 1. Functional Dependencies (FD)
An FD denoted by X → Y specifies that the value of X uniquely determines the value of Y.

## 2. Normal Forms Hierarchy
1. **1NF:** Atomic values in each column; no multivalued attributes.
2. **2NF:** In 1NF and no partial dependency (no non-prime attribute depends on a proper subset of any candidate key).
3. **3NF:** In 2NF and no transitive dependency. If X → Y, then X is a superkey OR Y is a prime attribute.
4. **BCNF:** Stricter than 3NF. For every non-trivial X → Y, X MUST be a superkey.

## 3. SPPU Examination Tips
- Always compute attribute closures first.
- If an FD has a prime attribute on the right side, it satisfies 3NF even if the left side is not a superkey.`,
    read_time_minutes: 8,
    is_free_preview: true,
    is_premium: false,
    content_status: 'PUBLISHED',
    author_id: 'usr-admin-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_QUIZZES: Quiz[] = [
  {
    id: 'quiz-dbms-norm',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-3',
    title: 'DBMS Unit 3: Normalization Mastery Quiz',
    description: '15 High-yield multiple choice questions testing 1NF, 2NF, 3NF, and BCNF concepts from SPPU papers.',
    duration_minutes: 15,
    total_questions: 2,
    passing_score: 60,
    difficulty: 'EXAM_STANDARD',
    is_premium: false,
    content_status: 'PUBLISHED',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'qq-1',
    quiz_id: 'quiz-dbms-norm',
    question_text: 'Under which normal form is a relation guaranteed to eliminate transitive functional dependencies?',
    options: [
      'First Normal Form (1NF)',
      'Second Normal Form (2NF)',
      'Third Normal Form (3NF)',
      'Boyce-Codd Normal Form (BCNF)',
    ],
    correct_option_index: 2,
    explanation: '3NF strictly mandates that no non-prime attribute depends transitively on a candidate key.',
    marks: 1,
    order_index: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'qq-2',
    quiz_id: 'quiz-dbms-norm',
    question_text: 'Which normal form always guarantees dependency preservation?',
    options: ['3NF', 'BCNF', '4NF', '5NF'],
    correct_option_index: 0,
    explanation: '3NF guarantees dependency preservation, whereas BCNF decomposition may not always preserve all functional dependencies.',
    marks: 1,
    order_index: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-free',
    code: 'FREE_EXPLORER',
    name: 'Free Explorer',
    description: 'Full SPPU syllabus structure, basic notes, select PYQ papers.',
    product_type: 'SUBJECT_PASS',
    price_inr: 0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-sub-dbms',
    code: 'SUB_DBMS_PASS',
    name: 'DBMS Single Subject Pass',
    description: 'Complete solved 2/5/10-mark answers, PYQ intelligence, and 5-hour Exam Mode.',
    product_type: 'SUBJECT_PASS',
    subject_id: 'sub-dbms',
    price_inr: 49,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-sem-comp',
    code: 'SEM_COMP_PASS',
    name: 'SE Computer Semester Pass',
    description: 'All 5 SE Computer subjects unlocked for the entire semester.',
    product_type: 'SEMESTER_PASS',
    semester_id: 'sem-3',
    price_inr: 199,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-sub-dsa',
    code: 'SUB_DSA_PASS',
    name: 'DSA Single Subject Pass',
    description: 'Complete Data Structures & Algorithms solved PYQs, notes, and rubrics.',
    product_type: 'SUBJECT_PASS',
    subject_id: 'sub-dsa',
    price_inr: 49,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-sub-os',
    code: 'SUB_OS_PASS',
    name: 'Operating Systems Single Subject Pass',
    description: 'Complete OS solved question bank, concurrency models, and CPU scheduling guides.',
    product_type: 'SUBJECT_PASS',
    subject_id: 'sub-os',
    price_inr: 49,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-crash-sem3',
    code: 'EXAM_CRASH_SPRINT',
    name: 'In-Sem 5-Hour Exam Crash Pass',
    description: 'Emergency 5-hour high-yield sprint plan for immediate exam preparation.',
    product_type: 'EXAM_CRASH',
    price_inr: 99,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_USERS: User[] = [
  {
    id: 'usr-admin-1',
    email: 'admin@scoreedge.in',
    // Salted scrypt hash for 'Admin@1234'
    password_hash: 'a1b2c3d4e5f60718:bd482c4a7975dc2cb90eadc075902254d3d5811928ced1c27c471fe3efad35b79fe869c63781ff07c7c415e973f786e427fec6c3332642570aef6989b7defb62',
    full_name: 'ScoreEdge Administrator',
    role: 'ADMIN',
    department: 'Computer Engineering',
    branch_code: 'COMP',
    academic_year: 'BE',
    year_number: 4,
    semester_number: 8,
    pattern: '2024 Pattern (NEP)',
    target_sgpa: 9.8,
    avatar_url: null,
    email_verified: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 1. FE Student: Aarav Deshmukh (First Year, Semester 2 - Computer Engineering)
  {
    id: 'usr-student-fe-comp',
    email: 'aarav.deshmukh@sppu.ac.in',
    password_hash: 'b2c3d4e5f6a10829:d3558071af2b4bef6ded4c2f86c8ec8dc40ac51447d8b41854de723aa3689c52250f61f43d93432a9d35bea07823dfc9e564e5a408b18a6f07726a9767e8fdfa',
    full_name: 'Aarav Deshmukh',
    role: 'STUDENT',
    department: 'Computer Engineering',
    branch_code: 'COMP',
    academic_year: 'FE',
    year_number: 1,
    semester_number: 2,
    pattern: '2024 Pattern (NEP)',
    target_sgpa: 9.4,
    avatar_url: null,
    email_verified: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 2. SE Student: Sneha Kulkarni (Second Year, Semester 4 - Computer Engineering)
  {
    id: 'usr-student-se-comp',
    email: 'sneha.kulkarni@sppu.ac.in',
    password_hash: 'b2c3d4e5f6a10829:d3558071af2b4bef6ded4c2f86c8ec8dc40ac51447d8b41854de723aa3689c52250f61f43d93432a9d35bea07823dfc9e564e5a408b18a6f07726a9767e8fdfa',
    full_name: 'Sneha Kulkarni',
    role: 'STUDENT',
    department: 'Computer Engineering',
    branch_code: 'COMP',
    academic_year: 'SE',
    year_number: 2,
    semester_number: 4,
    pattern: '2024 Pattern (NEP)',
    target_sgpa: 9.2,
    avatar_url: null,
    email_verified: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 3. TE Student: Rohan Patil (Third Year, Semester 6 - Information Technology)
  {
    id: 'usr-student-te-it',
    email: 'rohan.patil@sppu.ac.in',
    password_hash: 'b2c3d4e5f6a10829:d3558071af2b4bef6ded4c2f86c8ec8dc40ac51447d8b41854de723aa3689c52250f61f43d93432a9d35bea07823dfc9e564e5a408b18a6f07726a9767e8fdfa',
    full_name: 'Rohan Patil',
    role: 'STUDENT',
    department: 'Information Technology',
    branch_code: 'IT',
    academic_year: 'TE',
    year_number: 3,
    semester_number: 6,
    pattern: '2019 Pattern',
    target_sgpa: 8.9,
    avatar_url: null,
    email_verified: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 4. BE Student: Ananya Joshi (Final Year, Semester 8 - AI & Data Science)
  {
    id: 'usr-student-be-aids',
    email: 'ananya.joshi@sppu.ac.in',
    password_hash: 'b2c3d4e5f6a10829:d3558071af2b4bef6ded4c2f86c8ec8dc40ac51447d8b41854de723aa3689c52250f61f43d93432a9d35bea07823dfc9e564e5a408b18a6f07726a9767e8fdfa',
    full_name: 'Ananya Joshi',
    role: 'STUDENT',
    department: 'Artificial Intelligence & Data Science',
    branch_code: 'AI-DS',
    academic_year: 'BE',
    year_number: 4,
    semester_number: 8,
    pattern: '2019 Pattern',
    target_sgpa: 9.6,
    avatar_url: null,
    email_verified: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // 5. SE Student: Vikram Shinde (Second Year, Semester 3 - Electronics & Telecommunication)
  {
    id: 'usr-student-se-entc',
    email: 'vikram.shinde@sppu.ac.in',
    password_hash: 'b2c3d4e5f6a10829:d3558071af2b4bef6ded4c2f86c8ec8dc40ac51447d8b41854de723aa3689c52250f61f43d93432a9d35bea07823dfc9e564e5a408b18a6f07726a9767e8fdfa',
    full_name: 'Vikram Shinde',
    role: 'STUDENT',
    department: 'Electronics & Telecommunication',
    branch_code: 'E&TC',
    academic_year: 'SE',
    year_number: 2,
    semester_number: 3,
    pattern: '2024 Pattern (NEP)',
    target_sgpa: 8.7,
    avatar_url: null,
    email_verified: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Default legacy student user
  {
    id: 'usr-student-1',
    email: 'student@sppu.ac.in',
    password_hash: 'b2c3d4e5f6a10829:d3558071af2b4bef6ded4c2f86c8ec8dc40ac51447d8b41854de723aa3689c52250f61f43d93432a9d35bea07823dfc9e564e5a408b18a6f07726a9767e8fdfa',
    full_name: 'Prathamesh Jadhav',
    role: 'STUDENT',
    department: 'Computer Engineering',
    branch_code: 'COMP',
    academic_year: 'SE',
    year_number: 2,
    semester_number: 4,
    pattern: '2024 Pattern (NEP)',
    target_sgpa: 9.2,
    avatar_url: null,
    email_verified: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_ENTITLEMENTS: Entitlement[] = [
  {
    id: 'ent-1',
    user_id: 'usr-student-1',
    product_id: 'prod-sem-comp',
    semester_id: 'sem-3',
    access_scope: 'SEMESTER_ALL',
    expires_at: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_PROGRESS: StudentProgress[] = [
  {
    id: 'prog-1',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-3',
    topic_id: 'topic-norm-3nf',
    item_type: 'TOPIC',
    item_id: 'topic-norm-3nf',
    is_completed: true,
    last_activity_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days ago
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prog-2',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-3',
    topic_id: 'topic-norm-bcnf',
    item_type: 'TOPIC',
    item_id: 'topic-norm-bcnf',
    is_completed: true,
    last_activity_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prog-3',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-3',
    topic_id: 'topic-norm-fd',
    item_type: 'TOPIC',
    item_id: 'topic-norm-fd',
    is_completed: true,
    last_activity_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prog-4',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-3',
    topic_id: 'topic-norm-3nf',
    item_type: 'PYQ',
    item_id: 'q-dbms-3nf-bcnf',
    is_completed: true,
    last_activity_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Private record for student-2 to verify data privacy
  {
    id: 'prog-student2-1',
    user_id: 'usr-student-2',
    subject_id: 'sub-dbms',
    unit_id: 'unit-dbms-1',
    topic_id: 'topic-er-model',
    item_type: 'TOPIC',
    item_id: 'topic-er-model',
    is_completed: true,
    last_activity_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_STUDY_PLANS: StudyPlan[] = [
  {
    id: 'plan-1',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    title: 'Emergency 5-Hour DBMS Crash Plan',
    duration_type: '5h',
    available_hours: 5.0,
    completion_rate: 50.0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_STUDY_PLAN_TASKS: StudyPlanTask[] = [
  {
    id: 'task-1',
    study_plan_id: 'plan-1',
    topic_id: 'topic-norm-3nf',
    task_title: 'Unit 3: Normalization (3NF & BCNF Exam Answers)',
    task_type: 'MUST_READ_NOTE',
    estimated_minutes: 60,
    priority: 'MUST_STUDY',
    is_completed: true,
    order_index: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'task-2',
    study_plan_id: 'plan-1',
    topic_id: 'topic-trans-acid',
    task_title: 'Unit 4: ACID Properties & Serializability Review',
    task_type: 'MUST_READ_NOTE',
    estimated_minutes: 60,
    priority: 'MUST_STUDY',
    is_completed: false,
    order_index: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_ORDERS: Order[] = [];
export const SEED_PAYMENTS: Payment[] = [];

export const SEED_QUIZ_ATTEMPTS: QuizAttempt[] = [
  {
    id: 'qa-1',
    user_id: 'usr-student-1',
    quiz_id: 'quiz-dbms-norm',
    score: 9,
    max_score: 10,
    percentage: 90,
    time_taken_seconds: 480,
    completed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    answers_json: { q1: 0, q2: 1, q3: 0 },
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'qa-2',
    user_id: 'usr-student-1',
    quiz_id: 'quiz-dbms-trans',
    score: 4,
    max_score: 10,
    percentage: 40, // Weak performance!
    time_taken_seconds: 520,
    completed_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    answers_json: { q1: 2, q2: 3, q3: 1 },
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  // Private attempt for student-2
  {
    id: 'qa-student2-1',
    user_id: 'usr-student-2',
    quiz_id: 'quiz-dbms-norm',
    score: 10,
    max_score: 10,
    percentage: 100,
    time_taken_seconds: 300,
    completed_at: new Date().toISOString(),
    answers_json: {},
    created_at: new Date().toISOString(),
  },
];

export const SEED_STUDY_SESSIONS: StudySession[] = [
  {
    id: 'session-1',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    duration_minutes: 45,
    topics_covered: ['topic-norm-3nf', 'topic-norm-bcnf'],
    questions_practiced: 3,
    notes_reviewed: 2,
    started_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'session-2',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    duration_minutes: 30,
    topics_covered: ['topic-trans-acid'],
    questions_practiced: 1,
    notes_reviewed: 1,
    started_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SEED_EXAM_MODE_RECORDS: ExamModeRecord[] = [
  {
    id: 'em-rec-1',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    duration_type: '5h',
    total_tasks: 4,
    completed_tasks: 2,
    completion_rate: 50.0,
    status: 'IN_PROGRESS',
    completed_at: null,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SEED_REVISION_RECORDS: RevisionRecord[] = [
  {
    id: 'rev-1',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    topic_id: 'topic-norm-3nf',
    revision_count: 2,
    confidence_level: 'CONFIDENT',
    last_revised_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days ago -> needs revision
    next_recommended_revision_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rev-2',
    user_id: 'usr-student-1',
    subject_id: 'sub-dbms',
    topic_id: 'topic-trans-2pl',
    revision_count: 1,
    confidence_level: 'NEEDS_PRACTICE',
    last_revised_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    next_recommended_revision_at: new Date().toISOString(), // Due now!
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SEED_VERIFICATION_RECORDS: VerificationRecord[] = [];

export { SEED_ANALYTICS_EVENTS } from '../analytics/seed';

